<a href="https://colab.research.google.com/github/JakeOh/202208_itw_java134_lab_python/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# `np.ndarray` 속성들

In [25]:
arr = np.ones(shape=(2, 3))  #> 모든 원소가 1.0인 (2, 3) 모양의 배열을 생성.

In [26]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [28]:
arr.shape  # 배열의 모양: 배열의 각 축(axis)을 따라서 있는 원소의 개수

(2, 3)

In [29]:
arr.ndim  # 배열의 차원(dimension): 배열에서 축의 개수

2

In [30]:
arr.size  # 크기: 배열의 원소 전체 개수

6

In [31]:
arr = np.arange(10)
print(arr)
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)

[0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
ndim: 1
size: 10


# indexing

* Python list: `list[i], list[i][j], list[i][j][k], ...`
* numpy ndarray
    * `array[i], array[i][j], array[i][j][k], ...`
    * `array[i], array[i, j], array[i, j, k], ...`


In [32]:
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr[0]

array([1, 2, 3, 4])

In [34]:
arr[0, 0]

1

In [35]:
arr[0][0]

1

# slicing

## 1차원 배열 slicing

In [36]:
np.random.seed(1)
arr = np.random.randint(100, size=10)
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [37]:
arr[2:6]  # [2, 6) 범위의 원소들로 이루어진 부분집합(ndarray)

array([72,  9, 75,  5])

In [38]:
arr[:3]  # 첫 3개 원소 자르기

array([37, 12, 72])

In [39]:
arr[-3:]  # 마지막 3개 원소 자르기

array([64, 16,  1])

## 2차원 배열 slicing

In [40]:
np.random.seed(1)
arr = np.random.randint(100, size=(4, 5))
print(arr)

[[37 12 72  9 75]
 [ 5 79 64 16  1]
 [76 71  6 25 50]
 [20 18 84 11 28]]


In [41]:
# 첫 2개 row를 선택, 모든 column을 선택
arr[:2, :]

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1]])

In [42]:
arr[:2]

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1]])

In [44]:
# 첫 2개 row을 선택, 첫 3개 column 선택
arr[:2, :3]

array([[37, 12, 72],
       [ 5, 79, 64]])

In [45]:
arr[:1, :1]

array([[37]])

# Shape 변경

* `np.ndarray.reshape(shape)`
* `np.ndarray.ravel()`
* `np.ndarray.flatten()`
* `np.newaxis` 속성 이용


## reshape

In [46]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
# arr_1d 배열을 (4, 3) shape의 2차원 배열로 변환 -> 모양이 변환된 새로운 배열이 리턴.
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [57]:
# reshape을 할 때 자동으로 계산될 수 있는 차원 값에는 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((3, -1))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
arr_2d = arr_1d.reshape((-1, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
arr_2d.reshape((3*4,))  # reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
arr_2d.reshape((-1,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## `ravel` vs `flatten`

* `ravel`: 1차원으로 변환된 배열의 **view**를 리턴. 배열은 1개이고, 단지 모양만 다르게 보여주는 것.
* `flatten`: 1차원으로 변환된 배열의 **복사본**을 리턴. 원본 배열과는 별개의 새로운 배열이 생성됨.


In [64]:
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
flattened = arr_2d.flatten()

In [67]:
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [69]:
flattened[0] = 100
print(flattened)
print(arr_2d)  # 1차원으로 변환된 배열의 원소를 변경하는 것이 2차원 배열에 영향을 미치지 않음.

[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [70]:
raveled = arr_2d.ravel()
print(raveled)
print(arr_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
raveled[0] = 100
print(raveled)
print(arr_2d)  # 1차원 배열의 수정 내용은 원본 2차원 배열에도 적용.

[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 